### ISSUE TITLE
Allow assets to be excluded

### ISSUE THREAD

**Issue by lettertwo** [lettertwo/appcache-webpack-plugin#2]
Conversely, maybe allow only some assets to be included.

``` coffeescript
new AppcachePlugin
  include: [
    /.*\.js$/
    /.*\.svg$/
  ]
  exclude: [
    /.*\/.js\/.map$/
    /\/thing\.js$/
    /\/icons\/.*\.svg$/
  ]
```

**Comment by chiplay** [comment]
@lettertwo right now all of my sourcemap files are getting included in the manifest as part of the production build. I definitely don't want users downloading those huge files :) Would the `exclude` solution your proposing above by the only way to solve my issue?

**Comment by chiplay** [comment]
I'm going to go ahead and use this in a fork unless your thinking about implementing this any time soon:

```
// Exclude sourcemap files from manifest
if (path.extname(key) !== '.map') appCache.addAsset(key);
```

**Comment by chiplay** [comment]
@lettertwo well, I went ahead and took a stab at it :) I'm terrible at coffeescript and decided to pull in underscore to make it a bit easier, but feel free refactor to use if you want:

```
Object.keys(compilation.assets).forEach(function(key) {
    if (_.isArray(_this.include)) {
      if (_.some(_this.include, function(exp) { return exp.test(key); })) appCache.addAsset(key);
      return;
    }
    if (_.isArray(_this.exclude)) {
      if (_.every(_this.exclude, function(exp) { return !exp.test(key); })) appCache.addAsset(key);
      return;
    }
    appCache.addAsset(key);
  });
```

**Comment by vshjxyz** [comment]
Hey, check #7 out :smile:
