### ISSUE TITLE
Manifest file lists itsself

### ISSUE THREAD

**Issue by andru** [lettertwo/appcache-webpack-plugin#4]
Edit: Generalized the issue, since it occurs with all configs.

`manifest.appcache` is listed as the last item in the `CACHE MANIFEST` section of the manifest file...

```
CACHE MANIFEST
# 0d69541ac542a8c13716

[...snipped lots of stuff...]
index.html
manifest.appcache
```

While, as far as I can tell, this doesn't cause any problems, it doesn't seem like a good idea.

**Comment by hcschuetz** [comment]
This does not happen for me.

Could it be that you are somehow referencing and loading the manifest file?  Perhaps the manifest from an earlier webpack run is matched by some regexp or globbing, either in your webpack configuration or indirectly in some other loaded file?

Or are you using jordansexton's fork?  (That seems to include a path passed as an option.)

**Comment by chiplay** [comment]
@andru @hcschuetz  this was happening for me using grunt-webpack with a falty `plugins` config (pulled from the some tutorial) that was causing all the plugins to be run twice, adding the `manifest.appcache` the second time around.

**Comment by lettertwo** [comment]
@andru I'm going to close this, as I believe @chiplay's comment about duplicate plugins may be at fault. If that is not the case, and you are still seeing this behavior, feel free to re-open.
